POST http://localhost:1337/orders
Content-Type: application/json

{
    "_id": "Order-4",
    "product": "cap",
    "title": "red corduroy cap",
    "specs": true
}

### Getting all orders
GET http://localhost:1337/orders


### Get a specific order
GET http://localhost:1337/orders/Order-2

### Delete an order
DELETE http://localhost:1337/orders/Order-3